version: "3"
services:
       node-kit:
           container_name: node-kit
           image: raj77aws/node-kit-repo:v2
           restart: always
           ports:
             - "4001:4001"
           links:
             - mongo

       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'